testdir20 try 2.

diff --git a/testdir20/configure b/testdir20/configure
--- a/testdir20/configure
+++ b/testdir20/configure
@@ -7294,9 +7294,9 @@ printf "%s\n" "$gl_cv_decl_null_works" >&6; }
     GL_GENERATE_STDDEF_H=true
   fi
 
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for unreachable" >&5
-printf %s "checking for unreachable... " >&6; }
-if test ${gl_cv_func_unreachable+y}
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for unreachable in C" >&5
+printf %s "checking for unreachable in C... " >&6; }
+if test ${gl_cv_c_func_unreachable+y}
 then :
   printf %s "(cached) " >&6
 else case e in #(
@@ -7315,9 +7315,9 @@ unreachable ();
 _ACEOF
 if ac_fn_c_try_link "$LINENO"
 then :
-  gl_cv_func_unreachable=yes
+  gl_cv_c_func_unreachable=yes
 else case e in #(
-  e) gl_cv_func_unreachable=no ;;
+  e) gl_cv_c_func_unreachable=no ;;
 esac
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.beam \
@@ -7325,11 +7325,43 @@ rm -f core conftest.err conftest.$ac_objext conftest.beam \
      ;;
 esac
 fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $gl_cv_func_unreachable" >&5
-printf "%s\n" "$gl_cv_func_unreachable" >&6; }
-  if test $gl_cv_func_unreachable = no; then
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $gl_cv_c_func_unreachable" >&5
+printf "%s\n" "$gl_cv_c_func_unreachable" >&6; }
+  if test $gl_cv_c_func_unreachable = no; then
     GL_GENERATE_STDDEF_H=true
   fi
+  if test "$CXX" != no; then
+                    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for unreachable in <stddef.h> in C++" >&5
+printf %s "checking for unreachable in <stddef.h> in C++... " >&6; }
+if test ${gl_cv_cxx_func_unreachable+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e)               cat > conftest.cpp <<\EOF
+#include <stddef.h>
+int main (void) { unreachable (); }
+EOF
+       gl_command="$CXX $CXXFLAGS $CPPFLAGS -c conftest.cpp"
+       if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$gl_command\""; } >&5
+  (eval $gl_command) 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+         gl_cv_cxx_func_unreachable=yes
+       else
+         gl_cv_cxx_func_unreachable=no
+       fi
+       rm -fr conftest*
+       ;;
+esac
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $gl_cv_cxx_func_unreachable" >&5
+printf "%s\n" "$gl_cv_cxx_func_unreachable" >&6; }
+    if test $gl_cv_cxx_func_unreachable = no; then
+      GL_GENERATE_STDDEF_H=true
+    fi
+  fi
+  GL_GENERATE_STDDEF_H=true        # XXX
 
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether nullptr_t needs <stddef.h>" >&5
 printf %s "checking whether nullptr_t needs <stddef.h>... " >&6; }
@@ -7678,12 +7710,19 @@ then :
 else case e in #(
   e) if test "$cross_compiling" = yes
 then :
-  case "$host_os" in
-                             # Guess 'no' on native Windows.
-          mingw* | windows*) gl_cv_header_working_fcntl_h='no' ;;
-          *)                 gl_cv_header_working_fcntl_h=cross-compiling ;;
-        esac
-
+  case $host_os,$gl_cross_guess_normal in #(
+  # The O_DIRECTORY test is known to fail on Mac OS X 10.4.11 (2007)
+          # (see <https://bugs.gnu.org/78509#95>)
+          # and to succeed on Mac OS X 10.5.8 [darwin9.8.0] (2009).
+          # Guess it fails on Mac OS X 10.4.x and earlier.
+          darwin[0-8].*yes) :
+    gl_cv_header_working_fcntl_h="guessing no (bad O_DIRECTORY)" ;; #(
+  # Known to be "no" on native MS-Windows.
+          mingw* | windows*) :
+    gl_cv_header_working_fcntl_h=no ;; #(
+  *) :
+    gl_cv_header_working_fcntl_h=$gl_cross_guess_normal ;;
+esac
 else case e in #(
   e) cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
@@ -7696,16 +7735,23 @@ else case e in #(
            # include <stdlib.h>
            # defined sleep(n) _sleep ((n) * 1000)
            #endif
+           #include <errno.h>
            #include <fcntl.h>
 
 
 $gl_mda_defines
 
+           #ifndef O_DIRECTORY
+            #define O_DIRECTORY 0
+           #endif
            #ifndef O_NOATIME
             #define O_NOATIME 0
            #endif
            #ifndef O_NOFOLLOW
             #define O_NOFOLLOW 0
+           #endif
+           #ifndef O_SEARCH
+            #define O_SEARCH O_RDONLY
            #endif
            static int const constants[] =
             {
@@ -7718,6 +7764,14 @@ main (void)
 {
 
             int result = !constants;
+
+            {
+              int fd = open ("confdefs.h", O_SEARCH | O_DIRECTORY);
+              result |= ! (fd < 0 && errno == ENOTDIR);
+              if (0 <= fd)
+                close (fd);
+            }
+
             #if HAVE_SYMLINK
             {
               static char const sym[] = "conftest.sym";
@@ -7789,38 +7843,63 @@ then :
   gl_cv_header_working_fcntl_h=yes
 else case e in #(
   e) case $? in #(
-        4) gl_cv_header_working_fcntl_h='no (bad O_NOFOLLOW)';; #(
-        64) gl_cv_header_working_fcntl_h='no (bad O_NOATIME)';; #(
-        68) gl_cv_header_working_fcntl_h='no (bad O_NOATIME, O_NOFOLLOW)';; #(
-         *) gl_cv_header_working_fcntl_h='no';;
-        esac ;;
+   1) :
+    gl_cv_header_working_fcntl_h="no (bad O_DIRECTORY)" ;; #(
+   4) :
+    gl_cv_header_working_fcntl_h="no (bad O_NOFOLLOW)" ;; #(
+   5) :
+    gl_cv_header_working_fcntl_h="no (bad O_DIRECTORY, O_NOFOLLOW)" ;; #(
+  64) :
+    gl_cv_header_working_fcntl_h="no (bad O_NOATIME)" ;; #(
+  65) :
+    gl_cv_header_working_fcntl_h="no (bad O_DIRECTORY, O_NOATIME)" ;; #(
+  68) :
+    gl_cv_header_working_fcntl_h="no (bad O_NOATIME, O_NOFOLLOW)" ;; #(
+  69) :
+    gl_cv_header_working_fcntl_h="no (bad O_DIRECTORY, O_NOATIME, O_NOFOLLOW)" ;; #(
+  *) :
+    gl_cv_header_working_fcntl_h="no" ;;
+esac ;;
 esac
 fi
 rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
   conftest.$ac_objext conftest.beam conftest.$ac_ext ;;
 esac
 fi
-
-     ;;
+ ;;
 esac
 fi
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $gl_cv_header_working_fcntl_h" >&5
 printf "%s\n" "$gl_cv_header_working_fcntl_h" >&6; }
 
   case $gl_cv_header_working_fcntl_h in #(
-  *O_NOATIME* | no | cross-compiling) ac_val=0;; #(
-  *) ac_val=1;;
-  esac
+  *O_DIRECTORY* | *no) :
+    gl_val=0 ;; #(
+  *) :
+    gl_val=1 ;;
+esac
 
-printf "%s\n" "#define HAVE_WORKING_O_NOATIME $ac_val" >>confdefs.h
+printf "%s\n" "#define HAVE_WORKING_O_DIRECTORY $gl_val" >>confdefs.h
 
 
   case $gl_cv_header_working_fcntl_h in #(
-  *O_NOFOLLOW* | no | cross-compiling) ac_val=0;; #(
-  *) ac_val=1;;
-  esac
+  *O_NOATIME* | *no) :
+    gl_val=0 ;; #(
+  *) :
+    gl_val=1 ;;
+esac
 
-printf "%s\n" "#define HAVE_WORKING_O_NOFOLLOW $ac_val" >>confdefs.h
+printf "%s\n" "#define HAVE_WORKING_O_NOATIME $gl_val" >>confdefs.h
+
+
+  case $gl_cv_header_working_fcntl_h in #(
+  *O_NOFOLLOW* | *no) :
+    gl_val=0 ;; #(
+  *) :
+    gl_val=1 ;;
+esac
+
+printf "%s\n" "#define HAVE_WORKING_O_NOFOLLOW $gl_val" >>confdefs.h
 
 
 
